apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api
  template:
    metadata:
      labels:
        app: video-api
    spec:
      containers:
      - name: video-api
        image: shahmikh1/video-api:latest  # <--- Updated this
        imagePullPolicy: Always                          # <--- Updated this
        ports:
        - containerPort: 5000
        env:                                 # <-- Add from here
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: video-api-secrets
              key: API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: video-api-service
  labels:                  #new added
    app: video-api         #new added
spec:
  type: NodePort
  selector:
    app: video-api
  ports:
  - name: http-web         #new added
    port: 5000
    targetPort: 5000
    nodePort: 30000
