apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: video-api-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus # Critical: Tells our specific Prometheus instance to pick this up
spec:
  selector:
    matchLabels:
      app: video-api
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http-web
    path: /metrics
